#pragma once

#define InitializationPhase "Initialization"
#define InputPhase "Input"
#define PrepingUpdatePhase "PrepingUpdate"
#define CleanUpPhase "CleanUp"
#define PostCleanUpPhase "PostCleanUp"
#define PreUpdatePhase "PreUpdate"
#define UpdatePhase "Update"
#define UpdateUnpausedPhase "UpdateUnpaused"
#define PostUpdatePhase "PostUpdate"
#define PostUpdateUnpausedPhase "PostUpdateUnpaused"
#define EndUpdatePhase "EndUpdate"
#define MovingPhase "Moving"
#define SteppingPhase "Stepping"
#define ValidatePhase "Validate"
#define DisplaySyncPhase "DisplaySync"
#define EndCleanUpPhase "EndCleanUp"
